name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: What version of the SDK are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: java-version
    attributes:
      label: Java Version
      description: What version of Java are you using?
      options:
        - "17"
        - "21"
        - "25"
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: regression
    attributes:
      label: Is this a regression?
      description: Did this work in a previous version?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: input
    id: worked-version
    attributes:
      label: Last Working Version
      description: If this is a regression, what version did this work in?
      placeholder: e.g., 0.9.0
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots
      placeholder: Additional information...
    validations:
      required: false
