name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: what
    attributes:
      label: What would you like?
      description: Describe the feature you'd like to see
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: Suggest how this could be implemented
      placeholder: This could be implemented by...
    validations:
      required: false

  - type: dropdown
    id: breaking-change
    attributes:
      label: Is this a breaking change?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: rfc
    attributes:
      label: Does this require an RFC?
      description: RFC is required when changing existing behavior or for new features that require research
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots
      placeholder: Additional information...
    validations:
      required: false
