#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


EXAMPLES_DIR = Path(__file__).resolve().parent
SOURCE_ROOT = EXAMPLES_DIR / "src/main/java"
EXAMPLE_PACKAGE_ROOT = SOURCE_ROOT / "software/amazon/lambda/durable/examples"
DEFAULT_OUTPUT = EXAMPLES_DIR / "template.yaml"
TEMPLATE_ANNOTATION = "ExampleTemplate"


@dataclass(frozen=True)
class ExampleFunction:
    class_name: str
    package_name: str
    suffix: str
    condition: str | None
    tracing: bool

    @property
    def logical_id(self) -> str:
        return f"{self.class_name}Function"

    @property
    def log_group_logical_id(self) -> str:
        return f"{self.logical_id}LogGroup"

    @property
    def handler(self) -> str:
        return f"{self.package_name}.{self.class_name}"

    @property
    def description(self) -> str:
        words = re.sub(r"(?<!^)(?=[A-Z])", " ", self.class_name)
        words = words.replace("Otel", "OTel").replace("X Ray", "X-Ray")
        return f"{words} Function ARN"


def kebab_case(name: str) -> str:
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "-", name).lower()


def read_package(source: str, path: Path) -> str:
    match = re.search(r"^package\s+([\w.]+);", source, flags=re.MULTILINE)
    if not match:
        raise ValueError(f"Missing package declaration: {path}")
    return match.group(1)


def is_top_level_durable_handler(source: str, class_name: str) -> bool:
    match = re.search(rf"public\s+(?:final\s+)?class\s+{class_name}\b(?P<header>[^\{{]*)\{{", source, re.DOTALL)
    return bool(match and "extends DurableHandler" in match.group("header"))


def read_template_annotation(source: str, class_name: str) -> tuple[str | None, bool]:
    class_match = re.search(rf"public\s+(?:final\s+)?class\s+{class_name}\b", source)
    if not class_match:
        return None, False

    prefix = source[: class_match.start()]
    matches = list(
        re.finditer(rf"@(?:[A-Za-z_][\w.]*\.)?{TEMPLATE_ANNOTATION}\s*(?:\((?P<body>.*?)\))?", prefix, re.DOTALL)
    )
    if not matches:
        return None, False

    body = matches[-1].group("body") or ""
    condition_match = re.search(r'condition\s*=\s*"([^"]+)"', body)
    tracing_match = re.search(r"tracing\s*=\s*(true|false)", body)
    condition = condition_match.group(1) if condition_match else None
    tracing = tracing_match.group(1) == "true" if tracing_match else False
    return condition, tracing


def discover_examples() -> list[ExampleFunction]:
    examples = []
    for path in sorted(EXAMPLE_PACKAGE_ROOT.rglob("*.java")):
        source = path.read_text(encoding="utf-8")
        class_name = path.stem
        if not is_top_level_durable_handler(source, class_name):
            continue

        condition, tracing = read_template_annotation(source, class_name)
        package_name = read_package(source, path)
        examples.append(
            ExampleFunction(
                class_name=class_name,
                package_name=package_name,
                suffix=kebab_case(class_name),
                condition=condition,
                tracing=tracing,
            )
        )
    return examples


def emit_function(lines: list[str], example: ExampleFunction) -> None:
    lines.extend(
        [
            f"  {example.logical_id}:",
            "    Type: AWS::Serverless::Function",
        ]
    )
    if example.condition:
        lines.append(f"    Condition: {example.condition}")
    lines.append(f"    DependsOn: {example.log_group_logical_id}")
    lines.extend(
        [
            "    Properties:",
            f'      FunctionName: !Sub "${{FunctionNamePrefix}}{example.suffix}"',
            f'      Handler: "{example.handler}"',
            "      Role: !Ref RoleArn",
        ]
    )
    if example.tracing:
        lines.extend(
            [
                "      Tracing: Active",
                "      Layers:",
                "        - !Sub",
                "          - arn:aws:lambda:${AWS::Region}:901920570463:layer:aws-otel-java-agent-${AdotArch}-ver-1-32-0:6",
                "          - AdotArch: amd64",
            ]
        )
    lines.append("")


def emit_log_group(lines: list[str], example: ExampleFunction) -> None:
    lines.extend(
        [
            f"  {example.log_group_logical_id}:",
            "    Type: AWS::Logs::LogGroup",
        ]
    )
    if example.condition:
        lines.append(f"    Condition: {example.condition}")
    lines.extend(
        [
            "    Properties:",
            f'      LogGroupName: !Sub "/aws/lambda/${{FunctionNamePrefix}}{example.suffix}"',
            "      RetentionInDays: 7",
            "",
        ]
    )


def render_template(examples: list[ExampleFunction]) -> str:
    lines = [
        "# This file is generated by examples/generate-template.py. Do not edit it by hand.",
        'AWSTemplateFormatVersion: "2010-09-09"',
        "Transform: AWS::Serverless-2016-10-31",
        "Description: AWS Lambda Durable Execution SDK Examples",
        "",
        "Parameters:",
        "  Architecture:",
        "    Type: String",
        "    Default: arm64",
        "    Description: Lambda Function Architecture",
        "    AllowedValues:",
        "      - x86_64",
        "      - arm64",
        "  JavaVersion:",
        "    Type: String",
        "    Default: 'java17'",
        "    Description: Java runtime version",
        "  FunctionNamePrefix:",
        "    Type: String",
        "    Default: ''",
        "    Description: Optional prefix for Lambda function names",
        "  RoleArn:",
        "    Type: String",
        "    Description: IAM Role ARN for Lambda function execution",
        "",
        "Conditions:",
        "  IsJava21OrLater:",
        "    !Or",
        "      - !Equals [!Ref JavaVersion, 'java21']",
        "      - !Equals [!Ref JavaVersion, 'java25']",
        "",
        "Globals:",
        "  Function:",
        "    Timeout: 900",
        "    MemorySize: 512",
        "    Architectures:",
        "      - !Ref Architecture",
        "    DurableConfig:",
        "      ExecutionTimeout: 300",
        "      RetentionPeriodInDays: 7",
        "    Runtime: !Ref JavaVersion",
        "    Environment:",
        "      Variables:",
        "        FUNCTION_NAME_PREFIX: !Ref FunctionNamePrefix",
        "",
        "Resources:",
    ]

    for example in examples:
        emit_log_group(lines, example)
        emit_function(lines, example)

    lines.append("Outputs:")
    for index, example in enumerate(examples):
        if index:
            lines.append("")
        lines.extend(
            [
                f"  {example.logical_id}:",
                f"    Description: {example.description}",
            ]
        )
        if example.condition:
            lines.append(f"    Condition: {example.condition}")
        lines.append(f"    Value: !GetAtt {example.logical_id}.Arn")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the examples SAM template from Java example handlers.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Path to write the generated template.")
    args = parser.parse_args()

    examples = discover_examples()
    if not examples:
        raise RuntimeError("No DurableHandler examples found")

    args.output.write_text(render_template(examples), encoding="utf-8")
    print(f"Generated {args.output} with {len(examples)} Lambda functions.")


if __name__ == "__main__":
    main()
