AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda Durable Execution SDK Examples

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Architectures:
      - arm64

Resources:
  SimpleStepExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: simple-step-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.SimpleStepExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:simple-step-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  WaitExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: wait-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.WaitExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:wait-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  RetryExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: retry-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.RetryExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:retry-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  WaitAtLeastExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: wait-at-least-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.WaitAtLeastExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:wait-at-least-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  WaitAtLeastInProcessExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: wait-at-least-in-process-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.WaitAtLeastInProcessExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:wait-at-least-in-process-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  RetryInProcessExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: retry-in-process-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.RetryInProcessExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:retry-in-process-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  GenericTypesExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: generic-types-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.GenericTypesExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:generic-types-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  CustomConfigExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: custom-config-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.CustomConfigExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:custom-config-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  LoggingExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: logging-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.LoggingExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:logging-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  ErrorHandlingExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: error-handling-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.ErrorHandlingExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:error-handling-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  CallbackExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: callback-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.CallbackExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:callback-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

  ManyAsyncStepsExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: many-async-steps-example
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.ManyAsyncStepsExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:many-async-steps-example"
    Metadata:
      Dockerfile: examples/Dockerfile
      DockerContext: ../
      DockerTag: durable-examples

Outputs:
  SimpleStepExampleFunction:
    Description: Simple Step Example Function ARN
    Value: !GetAtt SimpleStepExampleFunction.Arn

  SimpleStepExampleFunctionName:
    Description: Simple Step Example Function Name
    Value: !Ref SimpleStepExampleFunction

  WaitExampleFunction:
    Description: Wait Example Function ARN
    Value: !GetAtt WaitExampleFunction.Arn

  WaitExampleFunctionName:
    Description: Wait Example Function Name
    Value: !Ref WaitExampleFunction

  RetryExampleFunction:
    Description: Retry Example Function ARN
    Value: !GetAtt RetryExampleFunction.Arn

  RetryExampleFunctionName:
    Description: Retry Example Function Name
    Value: !Ref RetryExampleFunction

  WaitAtLeastExampleFunction:
    Description: Wait At Least Example Function ARN
    Value: !GetAtt WaitAtLeastExampleFunction.Arn

  WaitAtLeastExampleFunctionName:
    Description: Wait At Least Example Function Name
    Value: !Ref WaitAtLeastExampleFunction

  WaitAtLeastInProcessExampleFunction:
    Description: Wait At Least In Process Example Function ARN
    Value: !GetAtt WaitAtLeastInProcessExampleFunction.Arn

  WaitAtLeastInProcessExampleFunctionName:
    Description: Wait At Least In Process Example Function Name
    Value: !Ref WaitAtLeastInProcessExampleFunction

  RetryInProcessExampleFunction:
    Description: Retry In Process Example Function ARN
    Value: !GetAtt RetryInProcessExampleFunction.Arn

  RetryInProcessExampleFunctionName:
    Description: Retry In Process Example Function Name
    Value: !Ref RetryInProcessExampleFunction

  GenericTypesExampleFunction:
    Description: Generic Types Example Function ARN
    Value: !GetAtt GenericTypesExampleFunction.Arn

  GenericTypesExampleFunctionName:
    Description: Generic Types Example Function Name
    Value: !Ref GenericTypesExampleFunction

  CustomConfigExampleFunction:
    Description: Custom Config Example Function ARN
    Value: !GetAtt CustomConfigExampleFunction.Arn

  CustomConfigExampleFunctionName:
    Description: Custom Config Example Function Name
    Value: !Ref CustomConfigExampleFunction

  LoggingExampleFunction:
    Description: Logging Example Function ARN
    Value: !GetAtt LoggingExampleFunction.Arn

  LoggingExampleFunctionName:
    Description: Logging Example Function Name
    Value: !Ref LoggingExampleFunction

  ErrorHandlingExampleFunction:
    Description: Error Handling Example Function ARN
    Value: !GetAtt ErrorHandlingExampleFunction.Arn

  ErrorHandlingExampleFunctionName:
    Description: Error Handling Example Function Name
    Value: !Ref ErrorHandlingExampleFunction

  CallbackExampleFunction:
    Description: Callback Example Function ARN
    Value: !GetAtt CallbackExampleFunction.Arn

  CallbackExampleFunctionName:
    Description: Callback Example Function Name
    Value: !Ref CallbackExampleFunction

  ManyAsyncStepsExampleFunction:
    Description: Many Async Steps Example Function ARN
    Value: !GetAtt ManyAsyncStepsExampleFunction.Arn

  ManyAsyncStepsExampleFunctionName:
    Description: Many Async Steps Example Function Name
    Value: !Ref ManyAsyncStepsExampleFunction
