AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda Durable Execution SDK Examples

Parameters:
  Architecture:
    Type: String
    Default: arm64
    Description: Lambda Function Architecture
    AllowedValues:
      - x86_64
      - arm64
  DockerFile:
    Type: String
    Default: examples/Dockerfile
    Description: path to Dockerfile
  FunctionNameSuffix:
    Type: String
    Default: ''
    Description: Suffix to append to all function names

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Architectures:
      - !Ref Architecture

Resources:
  NoopExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - noop-example
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: [ "com.amazonaws.lambda.durable.examples.NoopExample::handleRequest" ]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  SimpleStepExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - simple-step-example
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.SimpleStepExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  SimpleInvokeExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'simple-invoke-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.SimpleInvokeExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
                - lambda:InvokeFunction
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:simple-invoke-example${FunctionNameSuffix}"
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: '*'
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  WaitExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'wait-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.WaitExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:wait-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  RetryExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'retry-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.RetryExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:retry-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  WaitAtLeastExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'wait-at-least-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.WaitAtLeastExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:wait-at-least-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  WaitAtLeastInProcessExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'wait-at-least-in-process-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.WaitAtLeastInProcessExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:wait-at-least-in-process-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  RetryInProcessExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'retry-in-process-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.RetryInProcessExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:retry-in-process-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  GenericTypesExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'generic-types-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.GenericTypesExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:generic-types-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  CustomConfigExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'custom-config-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.CustomConfigExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:custom-config-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  LoggingExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'logging-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.LoggingExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:logging-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  ErrorHandlingExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'error-handling-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.ErrorHandlingExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:error-handling-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  CallbackExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'callback-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.CallbackExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:callback-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  ManyAsyncStepsExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'many-async-steps-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.ManyAsyncStepsExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:many-async-steps-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

  ChildContextExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Join
        - ''
        - - 'child-context-example'
          - !Ref FunctionNameSuffix
      ImageConfig:
        Command: ["com.amazonaws.lambda.durable.examples.ChildContextExample::handleRequest"]
      DurableConfig:
        ExecutionTimeout: 300
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:CheckpointDurableExecutions
                - lambda:GetDurableExecutionState
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:child-context-example${FunctionNameSuffix}"
    Metadata:
      Dockerfile: !Ref DockerFile
      DockerContext: ../
      DockerTag: durable-examples

Outputs:
  NoopExampleFunction:
    Description: Noop Example Function ARN
    Value: !GetAtt NoopExampleFunction.Arn

  NoopExampleFunctionName:
    Description: Noop Example Function Name
    Value: !Ref NoopExampleFunction

  SimpleStepExampleFunction:
    Description: Simple Step Example Function ARN
    Value: !GetAtt SimpleStepExampleFunction.Arn

  SimpleStepExampleFunctionName:
    Description: Simple Step Example Function Name
    Value: !Ref SimpleStepExampleFunction

  SimpleInvokeExampleFunction:
    Description: Simple Invoke Example Function ARN
    Value: !GetAtt SimpleInvokeExampleFunction.Arn

  SimpleInvokeExampleFunctionName:
    Description: Simple Invoke Example Function Name
    Value: !Ref SimpleInvokeExampleFunction

  WaitExampleFunction:
    Description: Wait Example Function ARN
    Value: !GetAtt WaitExampleFunction.Arn

  WaitExampleFunctionName:
    Description: Wait Example Function Name
    Value: !Ref WaitExampleFunction

  RetryExampleFunction:
    Description: Retry Example Function ARN
    Value: !GetAtt RetryExampleFunction.Arn

  RetryExampleFunctionName:
    Description: Retry Example Function Name
    Value: !Ref RetryExampleFunction

  WaitAtLeastExampleFunction:
    Description: Wait At Least Example Function ARN
    Value: !GetAtt WaitAtLeastExampleFunction.Arn

  WaitAtLeastExampleFunctionName:
    Description: Wait At Least Example Function Name
    Value: !Ref WaitAtLeastExampleFunction

  WaitAtLeastInProcessExampleFunction:
    Description: Wait At Least In Process Example Function ARN
    Value: !GetAtt WaitAtLeastInProcessExampleFunction.Arn

  WaitAtLeastInProcessExampleFunctionName:
    Description: Wait At Least In Process Example Function Name
    Value: !Ref WaitAtLeastInProcessExampleFunction

  RetryInProcessExampleFunction:
    Description: Retry In Process Example Function ARN
    Value: !GetAtt RetryInProcessExampleFunction.Arn

  RetryInProcessExampleFunctionName:
    Description: Retry In Process Example Function Name
    Value: !Ref RetryInProcessExampleFunction

  GenericTypesExampleFunction:
    Description: Generic Types Example Function ARN
    Value: !GetAtt GenericTypesExampleFunction.Arn

  GenericTypesExampleFunctionName:
    Description: Generic Types Example Function Name
    Value: !Ref GenericTypesExampleFunction

  CustomConfigExampleFunction:
    Description: Custom Config Example Function ARN
    Value: !GetAtt CustomConfigExampleFunction.Arn

  CustomConfigExampleFunctionName:
    Description: Custom Config Example Function Name
    Value: !Ref CustomConfigExampleFunction

  LoggingExampleFunction:
    Description: Logging Example Function ARN
    Value: !GetAtt LoggingExampleFunction.Arn

  LoggingExampleFunctionName:
    Description: Logging Example Function Name
    Value: !Ref LoggingExampleFunction

  ErrorHandlingExampleFunction:
    Description: Error Handling Example Function ARN
    Value: !GetAtt ErrorHandlingExampleFunction.Arn

  ErrorHandlingExampleFunctionName:
    Description: Error Handling Example Function Name
    Value: !Ref ErrorHandlingExampleFunction

  CallbackExampleFunction:
    Description: Callback Example Function ARN
    Value: !GetAtt CallbackExampleFunction.Arn

  CallbackExampleFunctionName:
    Description: Callback Example Function Name
    Value: !Ref CallbackExampleFunction

  ManyAsyncStepsExampleFunction:
    Description: Many Async Steps Example Function ARN
    Value: !GetAtt ManyAsyncStepsExampleFunction.Arn

  ManyAsyncStepsExampleFunctionName:
    Description: Many Async Steps Example Function Name
    Value: !Ref ManyAsyncStepsExampleFunction

  ChildContextExampleFunction:
    Description: Child Context Example Function ARN
    Value: !GetAtt ChildContextExampleFunction.Arn

  ChildContextExampleFunctionName:
    Description: Child Context Example Function Name
    Value: !Ref ChildContextExampleFunction
