name: Slack Notifications

on:
  issues:
    types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]

permissions: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Send issue notification to Slack
        if: github.event_name == 'issues'
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_ISSUE }}
          webhook-type: incoming-webhook
          payload: |
            {
              "action": "${{ github.event.action }}",
              "issue_url": "${{ github.event.issue.html_url }}",
              "package_name": "${{ github.repository }}"
            }

      - name: Send pull request notification to Slack
        if: github.event_name == 'pull_request_target'
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_PR }}
          webhook-type: incoming-webhook
          payload: |
            {
              "action": "${{ github.event.action }}",
              "pr_url": "${{ github.event.pull_request.html_url }}",
              "package_name": "${{ github.repository }}"
            }