name: Notify Slack - Discussions

on:
  discussion:
    types: [created]

permissions: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send discussion notification to Slack
        uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_DISCUSSION }}
          webhook-type: incoming-webhook
          payload: |
            {
              "action": "${{ github.event.action }}",
              "discussion_url": "${{ github.event.discussion.html_url }}",
              "package_name": "${{ github.repository }}"
            }
